### ISSUE TITLE
Add an Option Rom Driver

### ISSUE THREAD

**Issue by archer-lawrence** [ionescu007/VisualUefi#1]
Great work on VisualUefi!
Is there any documentation on how to add an Option Rom driver.
Specifically, I am trying to add the UsbSerialDxe driver found in the OptionRom directory.

Thanks

**Comment by ionescu007** [comment]
I do have a sample locally. I'll try to put it up.

**Comment by archer-lawrence** [comment]
Thank you so much!!!

**Comment by ionescu007** [comment]
Hi!

You should now see this sample in VisualUefi if you updated to the latest release. This was a good suggestion, as so far all the samples were "homegrown", and this is actually a good sample on how to use existing EDK-II samples.
