### ISSUE TITLE
Missing two QEMU files

### ISSUE THREAD

**Issue by mcnameej** [ionescu007/VisualUefi#10]
Tried to run QEMU and nothing happened.  Then I noticed that it created a stderr.txt file, which contained:

    Could not open option rom 'kvmvapic.bin': No such file or directory
    qemu.exe: Initialization of device VGA failed: failed to find romfile "vgabios-stdvga.bin"

I obtained a *QEMU for Windows* installer from https://qemu.weilnetz.de/w64/, and used 7-Zip to extract `kvmvapic.bin` and `vgabios-stdvga.bin` from it.  I added those files to the debugger directory, and everything started working.

P.S.  VisualUefi is a great idea. Thank you!

**Comment by ionescu007** [comment]
I don't see these errors, and don't have these files. So I wonder if you're running QEMU incorrectly, without going through the VS Project File?

**Comment by mcnameej** [comment]
My initial attempt was via Visual Studio.  When nothing happened, I got the command line from samples.props and tried running it manually.  Same result (quick exit with no output).  That's when I noticed the stderr.txt file and went in search of the files it complained about.

By any chance, do you have a copy of QEMU installed into %ProgramFiles% on your system?  I don't.  If you do, QEMU is probably getting the missing files from there.

**Comment by ionescu007** [comment]
You nailed it. Thank you!!!
