### ISSUE TITLE
Openssl compiling error

### ISSUE THREAD

**Issue by fmj95817** [ionescu007/VisualUefi#11]
Hi Alex,
I built VisualUefi with VS2015, but project "OpenSSLlib" and "BaseCryptLib" in that solution failed to be compiled. The first error message sent by compiler is "size_t redefination". What has caused this problem?

regards,
Muju

**Comment by starsoftnl** [comment]
Hi Muju,
Same problem here. Did you find a solution for this?

regards,
Mark

**Comment by dannylion** [comment]
Well it's been a long while since you wrote this comment, but I ran into the same issue.

Make sure you use the edk2 version that Alex tailored for VisualUefi and it should just work.
[https://github.com/ionescu007/edk2](url)

**Comment by ionescu007** [comment]
Thanks for confirming that the one in this repo works as expected. I kept trying to find what the issue was!
