### ISSUE TITLE
C++ project

### ISSUE THREAD

**Issue by genuine-mysli** [ionescu007/VisualUefi#12]
Hi,

I wanted to write C++ code using the VisualUefi framework, but failed with quite some errors in the MdePkg.
Compiling the sme code as C-code works fine.

Is there  way to also write C++ code, or is this currently not supported?

**Comment by ionescu007** [comment]
I'm not sure if using C++ in UEFI environment is a good idea, even if you
can get it to compile :)

Best regards,
Alex Ionescu

**Comment by genuine-mysli** [comment]
understood, thank you
