### ISSUE TITLE
FtdiUsbSerialDriver usage example

### ISSUE THREAD

**Issue by genuine-mysli** [ionescu007/VisualUefi#13]
Hi,

in the VisualUefi package is the Ftdi driver as an example included.
In order to learn how to write own drivers, 
I would like to see how the Ftdi could be used within an own project.
Does someone have a code example where the Ftdi driver is being used?

Thank you.

**Comment by ionescu007** [comment]
Hi,

The driver exposes a protocol, which an application can locate and use. These are UEFI development basics that I suggest reading a book/tutorial on, or doing a training on the matter. It is outside the scope of this project.

Thanks!
