### ISSUE TITLE
How about other libraries?)

### ISSUE THREAD

**Issue by naggga** [ionescu007/VisualUefi#14]
Hi Sir, sorry for bothering you, I am new to EDK2. Previously, I was using the standard method of assembly without VS. Thank you for a wonderful decision. But in my application I use the function ShellExecute located in UefiShellLib (VisualUefi-master\edk2\ShellPkg\Library\UefiShellLib). Can I add this library (and others) for using it? If yes, how? Thank you for understanding.
![default](https://cloud.githubusercontent.com/assets/22893364/23253709/8f3c06d0-f9c6-11e6-9bc9-34443bd7f908.PNG)

**Comment by ionescu007** [comment]
Hi,

Support for ShellLib has now been added. Please see UefiApplication.
