### ISSUE TITLE
LNK2005: InternalMemSetMem is already set in BaseMemoryLib.lib(SetMem.obj)

### ISSUE THREAD

**Issue by Bowser1991** [ionescu007/VisualUefi#2]
Hi,
you did a great job!
If I'm trying to use an ASCII method like AsciiStrnCat(...) i got an linker warning : LNK2005: InternalMemSetMem is already set in BaseMemoryLib.lib(SetMem.obj)

Do you have any idea? 
PS: I commented out the SetMem.c code of BaseMemoryLib and after that it worked

Kind Regards an Merry Xmas
Daniel

**Comment by ionescu007** [comment]
Thanks for the bug report. I'll take a look...

**Comment by ionescu007** [comment]
Fixed by 699b174 .

**Comment by Bowser1991** [comment]
Thanks now it works
