### ISSUE TITLE
OpenSSLLib fails to compile 

### ISSUE THREAD

**Issue by knilecrack** [ionescu007/VisualUefi#21]
Hello Alex,

I want to thank you for sharing the project.

I'm not sure what am I doing wrong but I'm having issues compiling OpensslLib, after git clone --recursive and building with VS 2017 24 project compile 2 failed (BaseCryptLib and OpensslLib). Error that repeats is "Cannot open openssl/opensslconf.h". Since I already have compiled version of OpenSSL(1.1.0), I added new include folder where it resolves the issue with opensslconf but then another issues raise (missing machine/int_type, limit.h etc) so I guess that is not the solution.  Can you somehow point me in the right direction or should I use openssl 1.0.2?

**Comment by ionescu007** [comment]
Hi,

I just merged a fix for building with OpensslLib and that opensslconf.h issue.

That being said, you say you have an "already compiled version". Was it compiled for UEFI? Each openssllib is very different.

**Comment by knilecrack** [comment]
No, it was compiled for my system, not for UEFI, I guess you answered all my questions. I cloned repo now and everything is working perfectly, you made it looks so easy.

Thank you
