### ISSUE TITLE
Using unicode functions

### ISSUE THREAD

**Issue by Bowser1991** [ionescu007/VisualUefi#3]
First of alle Happy New Year !

I found an other issue. Whenever I'm trying to use a unicode function I get the linker error:

BaseLib.lib(SafeString.obj) : error LNK2001: Not resolved external symbol "__chkstk".

Here is my example
CHAR16 *str = L"";
str = CatSPrint(str, L"%s", "test");

I tried it with your sample.sln but it didn't work. Did I miss something or is it a bug ?

Kind regards
Daniel

**Comment by ionescu007** [comment]
Hi Daniel,

I think I know what's going on here. Will provide a fix shortly.

**Comment by ionescu007** [comment]
Hi Daniel,

As part of the property/toolchain rework, this issue should now be fixed. Thanks again!

**Comment by Bowser1991** [comment]
Hi,

thanks for this fix. I will test it within the next days and give you feedback

Kind regards
Daniel

**Comment by Bowser1991** [comment]
Hi,

I tested it today and it worked

Kind regards
Daniel
