### ISSUE TITLE
Unable to clone 2

### ISSUE THREAD

**Issue by alexgdi** [ionescu007/VisualUefi#33]
Unable to clone with 
git clone --recursive https://github.com/ionescu007/VisualUefi does not help.

Error: server does not allow request for unadvertised object

This helped fix the problem.
git submodule init
git submodule sync
git submodule foreach "(git checkout master; git pull)"

**Comment by DannyVlasenko** [comment]
Same problem. I tried to checkout submodules commits manually, but I can't find commits with provided hashes in submodules
