### ISSUE TITLE
I can't build OpensslLib and BaseCryptLib

### ISSUE THREAD

**Issue by AkumaRRR** [ionescu007/VisualUefi#39]
Hi, I cloned the git repository with

`git clone https://github.com/ionescu007/VisualUefi.git --recurse-submodules`

 set `NASM_PREFIX=C:\NASM` as system variable and compiled the whole solution but I wasn't able to build OpensslLib and BaseCryptLib.

Has anyone tried to compile from scratch lately? Is it still working?

**Comment by govind-mukundan** [comment]
Yes, I built it just now and it works fine. Note that your `NASM_PREFIX` environment variable should contain a `\` at the end - e.g. `C:\Program Files\NASM\`

**Comment by AkumaRRR** [comment]
Oh my...
Thank you! I just tried and it works.
