### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by eos33** [ionescu007/VisualUefi#5]
Hi Sir,
Sorry for bothering you.
I am new to EDK2 and trying to add the VisualUefi into my project.
How to install the "VisualUefi" that could work with EDK2?
(Copy all the files into EDK2 directory?)
I have set up the basic environment(VS2015 and Win32 BaseTools) that can compile the EDK2 applications successfully.

Thank you for your help.

**Comment by eos33** [comment]
sorry...I figured it out now.

I have copy the EDK2 source into the sub-directory VisualUefi\edk2\
and launch the VS2015 by clicking the VisualUefi\EDK-II\EDK-II.sln
But got some errors when building the library.
[Error.txt](https://github.com/ionescu007/VisualUefi/files/137580/Error.txt)

**Comment by Bowser1991** [comment]
Hi,
there are some problems with the dependencies. You could try to build the solution three or more times in a row. Each time you build the solution you should get less errors. Make sure you do not rebuild the projects (in Visual Stuido just press the F7 Key)

**Comment by ionescu007** [comment]
Hi,

Thanks for helping, Bowser1991. I'll see if I can make it stop failing multiple times so this behavior stops.

**Comment by ionescu007** [comment]
Fixed in recent master
