### ISSUE TITLE
Unable to clone

### ISSUE THREAD

**Issue by davidcie** [ionescu007/VisualUefi#6]
This project looks very promising and would love to make use of it in developing my little EFI app. However, I am unable to clone in Github for Windows app (it produces an error message which can be traced to an out of memory exception in the logs) and unable to clone in git shell which (1) complains that 'reference is not a tree: 7b40a4de48cfd3725c92ae2a68f57babda7a6ed2' when cloning the edk2 submodule and (2) that it is 'unable to connect to git.infradead.org' when cloning the openssl submodule. Are these known problems or some temporary connectivity/conf problem?

I also wonder why you decided to point to edk2 hosted on infraded rather than the (afaik official) [repo on github](http://github.com/tianocore/edk2)? Same thing with openssl.

**Comment by ionescu007** [comment]
Hi David,

The current edk2 and openssl branches cannot be compiled from real HEADs. edk2 currently uses a manual process where you manually have to create a patch/diff for the 1.0.2x version of openssl, and they are always scrambling to keep it up to date, especially with the frequent vulnerabilities in OpenSSL. An Intel employee has taken it up upon himself to fix this, by submitting upstream patches to both projects to allow OpenSSL head/master to build natively with EDK2. While those patches are still being integrated, he has provided repositories that he keeps up to date.

I am looking into why Github is failing at submodules. This was not a problem before.

**Comment by davidcie** [comment]
@ionescu007 thanks for an in-depth explanation, was not aware of these things — only started messing around with edk2 a week or so ago! 

Mailed Github support regarding cloning issues. For their part they're trying to nail down the OOM problem but as for shell cloning they said it would be best contacting the repo owner about this.

**Comment by ionescu007** [comment]
Try cloning the submodule by hand/manually, as in issue #7

**Comment by ionescu007** [comment]
This should work now. Thanks for bringing it up to my attention, let me know if you still have problems!

**Comment by davidcie** [comment]
Thanks for looking into it. Unfortunately it still does not work as expected:

![git](https://cloud.githubusercontent.com/assets/1963866/13724237/ca5d57a4-e87f-11e5-94cb-930df21b9034.png)

**Comment by ionescu007** [comment]
So it looks like openssl is being checked out correctly now, but not edk2? I will check the repo one more time. Submodules appear to be kind of broken if they cause so many issues. Can you try manually checking out edk2?

**Comment by ionescu007** [comment]
I have done one more pull/merge.

C:\Users\Alex Ionescu\Documents\GitHub\test> git clone --recursive https://github.com/ionescu007/VisualUefi
Cloning into 'VisualUefi'...
remote: Counting objects: 16070, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 16070 (delta 0), reused 0 (delta 0), pack-reused 16067 eceiving objects: 100% (16070/16070), 44.67 MiB | 2.95 MiB/s
Receiving objects: 100% (16070/16070), 46.53 MiB | 2.92 MiB/s, done.
Resolving deltas: 100% (5904/5904), done.
Checking connectivity... done.
Checking out files: 100% (14030/14030), done.
Submodule 'edk2' (git://git.infradead.org/users/dwmw2/edk2.git) registered for path 'edk2'
Submodule 'openssl' (git://git.infradead.org/users/dwmw2/openssl.git) registered for path 'openssl'
Cloning into 'edk2'...
remote: Counting objects: 213737, done.
remote: Compressing objects: 100% (50963/50963), done.
remote: Total 213737 (delta 162241), reused 207702 (delta 156275)
Receiving objects: 100% (213737/213737), 193.27 MiB | 17.66 MiB/s, done.
Resolving deltas: 100% (162241/162241), done.
Checking connectivity... done.
Submodule path 'edk2': checked out 'cbf0618e39a04d6d64abbd69c20e72d4e8c1d22a'
Cloning into 'openssl'...
remote: Counting objects: 191453, done.
remote: Compressing objects: 100% (40702/40702), done.
remote: Total 191453 (delta 155835), reused 185932 (delta 150337)
Receiving objects: 100% (191453/191453), 51.58 MiB | 13.62 MiB/s, done.
Resolving deltas: 100% (155835/155835), done.
Checking connectivity... done.
Submodule path 'openssl': checked out 'ffbc5b577d6283429c2348b23bca5eac46c80854'

This issue appears tixed now. Please re-open if you still see it.

**Comment by davidcie** [comment]
Works for me too now. Thanks for looking into it, fingers crossed this will not need to grab your attention anymore and will smoothly work from now on.
