### ISSUE TITLE
VisualUefi fails to clone submodule 'openssl'

### ISSUE THREAD

**Issue by mex20** [ionescu007/VisualUefi#7]
When executing "git clone --recursive https://github.com/ionescu007/VisualUefi" the Openssl submodule fails to clone. If you try and clone the repository separately, then it will build about 90% of the way and then the build will fail with: "c1 : fatal error C1083: Cannot open source file: '..\..\openssl\crypto\x509v3\v3_scts.c': No such file or directory"

**Comment by ionescu007** [comment]
Hi,

I am not sure why these sub-repos cannot be cloned. The URL is still valid as far as I can see, and others uses have cloned it successfully. I wonder if this is a bug in Github. Nevertheless, I will try deleting the sub-modules and adding them back from scratch.

When you cloned separately, did you make sure to clone the correct Openssl submodule? I.e.: git.infradead.org/users/dwmw2/openssl.git ?

**Comment by mex20** [comment]
Hi,

     I don't know why they cannot be cloned either. The EDK repo is seemingly cloning just fine. The Openssl repo fails when cloning and then the submodule update fails, then the submodules fail, and no repo is cloned. 

When I cloned separately, I cloned the repo that was in the openssl submodule file. It was the "git:infradead.org/users/dwmw2/openssl.git" repo. I looked at that repo and the official Openssl repo file list also, and the "crypto\x509v3\v3_scts.c" is not present in either the infradead or official Openssl repo.

**Comment by ionescu007** [comment]
This should work now. Thanks for bringing it up to my attention, let me know if you still have problems!

**Comment by aotles** [comment]
Hello,

I am also running into this problem.  When I downloaded the repo, my openssl directory contained only the "include" directory, so it would give me essentially the same error as the first post:
"c1 : fatal error C1083: Cannot open source file: '....\openssl\crypto\x509v3\v3_scts.c': No such file or directory"
