### ISSUE TITLE
Unable to build EDK-II project

### ISSUE THREAD

**Issue by Optionaled** [ionescu007/VisualUefi#9]
Reproduction:

1. Clone https://github.com/ionescu007/VisualUefi.git
2. run EDK-II.sln
3. Build

I get 87 build errors. Most seem to relate to edk2 being empty, but even after copying from edk2_old to edk2 it does not work.

**Comment by ionescu007** [comment]
Hi!

Let me take a look and refresh/update everything here.

**Comment by ionescu007** [comment]
Hi,

I have completely recreated all the repositories. Please try it now.

When you clone, make sure you use "--recursive" because this project uses submodules.
